databases:
  - name: recipe_app
    databaseName: recipe_app
    plan: free
services:
  - type: web
    name: RecipeApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipr_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free